# With some help from: https://gist.github.com/dgerosa/2e1f47a39180f39bde848e38243efa94

name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: .
      FILE: Neeraj_Butola_Resume
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Build PDF
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Convert LaTeX to HTML
        run: |
          pandoc "${{ env.DIR }}/${{ env.FILE }}.tex" -o ./website/index.html --from latex --to html
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts
      - name: Commit and push HTML
        uses: EndBug/add-and-commit@v9
        with:
          add: "website/"
          message: "Update website with HTML from LaTeX (via Pandoc)"
          default_author: github_actions
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true
